### ISSUE TITLE
Is there any SAR ship change detection dataset?

### ISSUE THREAD

**Issue by xyl-507** [wenhwu/awesome-remote-sensing-change-detection#8]
@wenhwu Thanks for your great work, but this repo hardly introduce SAR ship dataset or method. I want to know more about it, can you give me some useful information?thanks in advance.

**Comment by wenhwu** [comment]
Hi @xyl-507 
Thank you for your interest in this work

As far as I know, as of now, there are few public change detection datasets about SAR and almost no datasets about ship change detection.

More importantly, I think the task of ship change detection is of little significance in itself. Maybe you should pay attention to ship detection, not ship change detection because ships are not position-fixed objects on the surface of the earth like buildings. For the dataset and method of ship detection, may refer to [Airbus Ship Detection Challenge](https://www.kaggle.com/c/airbus-ship-detection) or [CAESAR-Radi/SAR-Ship-Dataset](https://github.com/CAESAR-Radi/SAR-Ship-Dataset).

Besides, you can refer to this [paper](https://www.mdpi.com/2072-4292/12/15/2460) for SAR change detection, in particular, the link to the dataset given in the paper, as shown in the figure below:
![SAR-A Survey of Change Detection Methods Based on Remote Sensing Images for Multi-Source and Multi-Objective Scenarios](https://user-images.githubusercontent.com/37108948/93665891-9c310a80-faac-11ea-979e-edee140377b5.png)

**Comment by xyl-507** [comment]
Thank you very much for your answer! yes, ship detection is more useful. it's my past research but unfortunately I begin to study on SAR change detection which is not hotter than target detection. Therefore, there is little information in this field. Thank you for your contribution and summary.
I'll study the information you gave me carefully. Thank you again!!! @wenhwu

**Comment by wenhwu** [comment]
@xyl-507 , thank you for your kind reply. What I want to emphasize is that you have to carefully define the problem you want to solve. I feel that what you might want to do is not ship change detection, but ship target tracking.

I'm closing this issue, but feel free to reach out if you have further concerns.
